server:
  port: 1112

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

security:
  oauth2:
    client:
      client-secret: 123456
      client-id: client4
      user-authorization-uri: http://localhost:8001/author/oauth/authorize
      access-token-uri: http://localhost:8001/author/oauth/token
      scope: all
      # 支持此处配置重定向地址，为true时，pre-established-redirect-uri不生效
      use-current-uri: false
      pre-established-redirect-uri: http://localhost:1112/login
    resource:
      user-info-uri: http://localhost:8002/api/hello
      jwt:
        key-uri: http://localhost:8001/author/oauth/token_key
        key-value: test-secret

zlt:
  sso:
    client-secret: 123456
    client-id: client5
    redirect-uri: http://localhost:1112/callback.html
    user-authorization-uri: http://localhost:8001/author/oauth/authorize
    access-token-uri: http://localhost:8001/author/oauth/token
    key-uri: http://localhost:8001/author/oauth/token_key
    user-info-uri: http://localhost:8002/api/hello
    # ??????????
    scope: all
mybatis:
  # mapper ??
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    # ??
    map-underscore-to-camel-case: true
    # ?? sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server.servlet.session.cookie.name=s1