server:
  port: 8002

spring:
  main:
    allow-circular-references: true
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: localhost # Redis 服务器地址
    port: 6379 # Redis 服务器连接端口
    password:  # Redis 服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/oauth2
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info

# 非对称加密 公钥
secret:
  # 公钥文件
  file: public.txt